name: Reusable Test

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version to use'
        required: false
        default: '1.20'
        type: string

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}

      - name: Run Unit Tests
        run: go test ./... -v
